spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:/Users/zhaoweih/GitHub/spring-config-repo
logging:
  file: ./config-server.log
  level: info
server:
  port: 8901
management:
  security:
    enabled: false
