spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:/Users/zhaoweih/GitHub/airwolf
          search-paths: spring-cloud-study/config-repo
logging:
  file: ./config-server.log
  level: info
server:
  port: 8901
management:
  security:
    enabled: false

